CREATE TABLE IF NOT EXISTS PRODUCT
(
    PRODUCT_ID   SERIAL PRIMARY KEY,
    NAME         VARCHAR(100),
    DESCRIPTION  VARCHAR(256),
    SKU          VARCHAR(100) not null,
    CREATED_DATE TIMESTAMP,
    UNIQUE (SKU)
);